flowchart TB
    A(("start")):::entryPoint --> B("Authorize User")
    B --> |"Authorized"| C(("Show Main Menu")):::state
    B --> |"Not Authorized"| End(("END")):::termination
    
    C --> |"✏️ Add"| D("Select Category"):::state
    C --> |"❌ Delete"| E("Check Expenses"):::state
    C --> |"📊 Charts"| F("Select Chart Type"):::state
    C --> |"📋 List"| G("Generate Expense List"):::state
    C --> |"💰 Budget"| H("Select Budget Action"):::state
    C --> |"⚙️ Settings"| I("Show Settings"):::state

    D --> J(("Select Subcategory"))
    J --> K(("Enter Price"))
    K --> L(("Save Expense"))
    L --> C

    E --> |"No expenses"| O(("No Expenses Message"))
    E --> |"Expenses exist"| P(("Show Paginated Expenses"))
    O --> C
    P --> C

    F --> |"Pie"| Q(("Generate Pie Chart"))
    F --> |"Histogram"| R(("Generate Histogram"))
    F --> |"Trend"| S(("Generate Trend Chart"))
    F --> |"Heatmap"| T(("Generate Heatmap"))
    Q --> C
    R --> C
    S --> C
    T --> C

    G --> U(("Generate Expense List"))
    U --> C

    H --> |"Set"| V(("Select Budget Category"))
    H --> |"Show"| W(("Show Budgets"))
    V --> X(("Enter Budget Amount"))
    W --> C
    X --> C

    I --> Y(("Show Settings"))
    Y --> Z(("Handle Settings Choice"))
    Z --> C

    subgraph Main
        A1(("cancel")):::entryPoint
        A1 --> C
    end
    
    style A fill:#00FF00,stroke:#000000,stroke-width:2px
    style B fill:#726000,stroke:#000000,stroke-width:2px
    style End fill:#FF0000,stroke:#000000,stroke-width:2px
    classDef state fill:#88443f,stroke:#000000,stroke-width:1px
    classDef entryPoint fill:#009c11, stroke:#42FF57, color:#ffffff
    classDef termination fill:#bb0007, stroke:#E60109, color:#ffffff
